#!/bin/bash

:<<'COMMENT'
Copyright (c) 2024 Austin Choi
See end of file for extended copyright information
COMMENT

shopt -s extglob

# Color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RESET='\033[0m'

# Get current directory
currentDirectory=$(pwd)

# Get script directory
cd "$(dirname "$0")/.."

projectDirectory=$(pwd)

cd ./tools

scriptDirectory=$(pwd)

# Get copyright information
year=$(date "+%Y")

# Project information for header and footer
if [ ! -f "../.project.env" ]
then
    echo -e "${RED}ERROR${RESET}: .project.env does not exist.\nCreate a project using the following command: ${GREEN}create${RESET}"
    exit 1
fi

source ../.project.env

# Get ignore list
if [ ! -f "../.project.ignore" ]
then
    echo -e "${RED}ERROR${RESET}: .project.ignore does not exist.\nCreate a .project.ignore file in the root directory of the project with the files and directories to ignore."
    exit 1
fi
ignoreList=$(cat ../.project.ignore)
filesToIgnore=()
directoriesToIgnore=()
for ignore in $ignoreList
do
  if [ ${ignore} == "[files]" ]
  then
    files=true
    directories=false
  elif [ ${ignore} == "[directories]" ]
  then
    files=false
    directories=true
  elif [ ${files} == true ]
  then
    filesToIgnore+=(${ignore})
  elif [ ${directories} == true ]
  then
    directoriesToIgnore+=(${ignore})
  fi
done

filesToIgnorePattern="!($(IFS="|"; echo "${filesToIgnore[*]}"))"
directoriesToIgnorePattern="!($(IFS="|"; echo "${directoriesToIgnore[*]}"))"

# Array storing each line to check for
copyrightLines=("Copyright (C) ${year} ${projectAuthor}" "See end of file for extended copyright information" "${projectName}" "${projectDescription}")

if [[ $licenseName == "All rights reserved" ]]
then
    copyrightLines+=("${licenseName}")
else
    copyrightLines+=("This code is licensed under the ${licenseName}" "Please see the LICENSE file in the root directory of this project for the full license details.")
fi

checkFileCopyright() {
    for line in "${copyrightLines[@]}"
    do
        if ! fgrep -q "${line}" "${1}"
        then
            echo -e "${RED}ERROR${RESET}: Copyright not found in ${1}"
            break
        fi
    done
}

traverseDirectories() {
    local currentDir="${1}"

    for dir in "${currentDir}"/*
    do
        ignore_file=false
        base=$(basename "${dir}")
        if [ -d "${dir}" ] && [[ ! ${base} == ${directoriesToIgnorePattern} ]]
        then
            continue
        elif [ -f "${dir}" ] && [[ ! ${base} == ${filesToIgnorePattern} ]]
        then
            continue
        elif [ -d "${dir}" ]
        then
            traverseDirectories "$dir"
        elif [ -f "${dir}" ] 
        then
            checkFileCopyright $dir
        fi
    done
}

traverseDirectories "$projectDirectory"

cd $currentDirectory

:<<'COMMENT'
Copyright (C) 2024 Austin Choi

All Rights Reserved.
This file is not under the license for the project and all rights are reserved to Austin Choi.

This script will check every file inside of the project repository and make sure they all have relavent copyright information

Repository of bash scripts for Austin Choi
COMMENT